apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fluentd.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fluentd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fluentd.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.output.host | quote }}
          - name: FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.output.port | quote }}
          # To avoid permission error, set FLUENT_UID to 0 in your Kubernetes configuration
          # Run as root: https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset
          - name: FLUENT_UID
            value: "0"
          # even if the two environment variables below not used, they are necessary
          # It is because the Docker image uses sed on the configuration file,
          # if these environment variables are not set, and since the ConfigMap is read-only,
          # the container will fail to start.
          - name: FLUENT_ELASTICSEARCH_USER
            value: "foo"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "bar"
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: config-volume-{{ template "fluentd.fullname" . }}
          mountPath: /fluentd/etc/
        - name: varlog
          mountPath: /var/log
      volumes:
        - name: config-volume-{{ template "fluentd.fullname" . }}
          configMap:
            name: {{ template "fluentd.fullname" . }}
        - name: varlog
          hostPath:
            path: /var/log
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    serviceAccountName: {{ template "fluentd.fullname" . }}
